#  Default rules for rsyslog.
#
auth,authpriv.*    action(type="omfile" file="/var/log/auth.log" template="RSYSLOG_TraditionalFileFormat")
*.*;auth,authpriv.none          -/var/log/syslog
kern.*                          -/var/log/kern.log
mail.*                          -/var/log/mail.log
mail.err                        /var/log/mail.err
*.emerg                         :omusrmsg:*
