auth,authpriv.*    action(type="omfile" file="/var/log/auth.log" template="RSYSLOG_TraditionalFileFormat")
*.*;auth,authpriv.none    action(type="omfile" file="/var/log/syslog" template="RSYSLOG_TraditionalFileFormat")
